on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  assign:
    name: Assign IDs
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4'
    - run: |
        go install github.com/google/osv/vulnfeeds/cmd/ids@latest
        ids -dir=./advisories -prefix PSF -format json
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
      env:
        GONOPROXY: github.com/google/osv
    - run: git diff --cached --quiet || git commit -m 'Assign IDs'
    - run: git push
